/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateTripRouteImport } from './routes/create-trip'
import { Route as TripTripIdRouteImport } from './routes/trip.$tripId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateTripRoute = CreateTripRouteImport.update({
  id: '/create-trip',
  path: '/create-trip',
  getParentRoute: () => rootRouteImport,
} as any)
const TripTripIdRoute = TripTripIdRouteImport.update({
  id: '/trip/$tripId',
  path: '/trip/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-trip': typeof CreateTripRoute
  '/trip/$tripId': typeof TripTripIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-trip': typeof CreateTripRoute
  '/trip/$tripId': typeof TripTripIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-trip': typeof CreateTripRoute
  '/trip/$tripId': typeof TripTripIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create-trip' | '/trip/$tripId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-trip' | '/trip/$tripId'
  id: '__root__' | '/' | '/create-trip' | '/trip/$tripId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateTripRoute: typeof CreateTripRoute
  TripTripIdRoute: typeof TripTripIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-trip': {
      id: '/create-trip'
      path: '/create-trip'
      fullPath: '/create-trip'
      preLoaderRoute: typeof CreateTripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/$tripId': {
      id: '/trip/$tripId'
      path: '/trip/$tripId'
      fullPath: '/trip/$tripId'
      preLoaderRoute: typeof TripTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateTripRoute: CreateTripRoute,
  TripTripIdRoute: TripTripIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
